###############################################################################
# Copyright (c) 2013, 2017 Perun Technologii DOOEL Skopje.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License
# Version 2.0 or the Svarog License Agreement (the "License");
# You may not use this file except in compliance with the License. 
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See LICENSE file in the project root for the specific language governing 
# permissions and limitations under the License.
#
###############################################################################
{
   "children":[
      {
         "user_code":"MODULE_NAME",
         "label_code":"codes.module_name",
         "children":[
            {
               "user_code":"ADMIN_CONSOLE",
               "label_code":"module_name.admin_console"
            },
            {
               "user_code":"OTHER",
               "label_code":"module_name.other"
            }
         ]
      },
      {
         "user_code":"PRIORITY",
         "label_code":"codes.priority",
         "children":[
            {
               "user_code":"1",
               "label_code":"priority.low"
            },
            {
               "user_code":"2",
               "label_code":"priority.normal"
            },
            {
               "user_code":"3",
               "label_code":"priority.high"
            }
         ]
      },
      {
         "user_code":"CATEGORY",
         "label_code":"codes.category",
         "children":[
            {
               "user_code":"INFO",
               "label_code":"category.info"
            },
            {
               "user_code":"TASK",
               "label_code":"category.task"
            },
            {
               "user_code":"REMARK",
               "label_code":"category.remark"
            }
         ]
      },
      {
         "user_code":"LINK_TYPE",
         "label_code":"master_repo.link_types",
         "children":[
            {
               "user_code":"MSG_TO",
               "label_code":"link_type.msg_to"
            },
            {
               "user_code":"MSG_CC",
               "label_code":"link_type.msg_cc"
            },
            {
               "user_code":"MSG_BCC",
               "label_code":"link_type.msg_bcc"
            }
         ]
      }
   ]
}
